### ISSUE TITLE
Hi! How this module works? It MIT Licensed? Demo? Thankyou!

### ISSUE THREAD

**Issue by arturmamedov** [yusidabcs/gallery#1]
Hi! How this module works? It MIT Licensed? Demo? Thankyou!

**Comment by yusidabcs** [comment]
Hello, I just used it to my personal project and not very good module. But I've update the readme. ty

**Comment by arturmamedov** [comment]
You intend to use it again? If it work i want to try it and maybe after go forward with development, what you think?
